# Pipeline: dataset-inference
# Run inference on a dataset using vLLM

pipeline: dataset-inference
description: "Run batch inference on a dataset with a model using vLLM"
tags: [dataset, inference, vllm]

entrypoint: core.pipelines.entrypoints.dataset_inference:run
environment: cloud

# --- Pipeline arguments ---
args:
  model_name:
    type: str
    required: true
    description: "HuggingFace model name or path"

  max_model_len:
    type: int
    default: 2048
    description: "vLLM max model len"

  dataset:
    path:
      type: str
      required: true
      description: "HuggingFace dataset name or local path"

    split:
      type: str
      default: "train"
      description: "Dataset split to use for training"

    format:
      type: str
      default: null
      description: "Format of the dataset ('chat' or 'text', if not specified it will be inferred from the prompts config or dataset structure)"

    text_format:
      type: str
      default: null
      description: "Format the text prompts. Use {instruction}/{input} as key to be replaced"

    system_prompt:
      type: str
      default: null
      description: "System prompt to prepend to all inputs"

    chat_template:
      type: str
      default: null
      description: "Chat template to format conversations"

    instruction_col:
      type: str
      default: "instruction"
      description: "Name of the column in the dataset containing the instruction text"

    input_col:
      type: str
      default: "input"
      description: "Name of the column in the dataset containing the inputs text"

    output_col:
      type: str
      default: "completion"
      description: "Name of the column in the dataset containing the completion text"

  sampling_params:
    seed:
      type: int
      default: 0
      description: "vllm seed"

    temperature:
      type: int
      default: 0
      description: "vllm temperature"

    max_tokens:
      type: int
      default: 2048
      description: "vllm max tokens"

    skip_special_tokens:
      type: bool
      default: False
      description: "vllm skip special tokens"

# --- Cloud infrastructure ---
cloud:
  image: "ghcr.io/dataesr/ml-hub/cuda-vllm:latest"
  name: "dataset-inference"
  command: ["/run.sh", "run_entrypoint"]
  gpu: 1
  flavor: "l4-1-gpu"
  volumes:
    - container: llm-configs
      mount: configs
    - container: llm-datasets
      mount: datasets
    - container: llm-completions
      mount: completions
      permission: RWD

# --- Tracking (MLflow) ---
tracking:
  project_name: "Default"
  enable_tracking: true
  enable_log_model: true
  enable_log_dataset: true
