FROM astral/uv:python3.11-trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
    zip \
    git \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# OVHAI CLI
RUN curl https://cli.gra.ai.cloud.ovh.net/ovhai-linux.zip -o ovhai-linux.zip && \
    unzip ovhai-linux.zip && \
    mkdir -p /bin && \
    mv ovhai /bin/ovhai && \
    rm -rf ovhai-linux.zip ovhai
RUN mkdir -p ~/.config/ovhai && curl -o ~/.config/ovhai/config.json https://cli.gra.ai.cloud.ovh.net/config.json

WORKDIR /app

# Install dependencies from workspace lock
COPY ./uv.lock .
COPY ./pyproject.toml .
COPY ./app/backend/pyproject.toml ./app/backend/pyproject.toml
COPY ./core/pyproject.toml ./core/pyproject.toml
RUN uv sync --frozen --no-cache

# Add source code
COPY ./core ./core
COPY ./app/backend ./app/backend

ENV PYTHONPATH="/app/core"

WORKDIR /app/app/backend

EXPOSE 8000

CMD ["uv", "run", "--no-sync", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]