[build-system]
requires = ["setuptools>=65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-core" 
version = "0.1.0"
description = "AI core library for all ml-hub services."
readme = "README.md"
requires-python = ">=3.11.5"
license = { text = "MIT" }
authors = [
    { name="Victor Barbier", email="victor.barbier@recherche.gouv.fr" }
]

dependencies = [
    "datasets==4.4.1",
    "huggingface-hub==0.35.3",
    "jsonref==1.1.0",
    "mlflow==3.6.0",
    "pandas==2.3.3",
    "pydantic==2.12.5",
    "pyyaml>=6.0",
    "rapidfuzz==3.14.5",
    "retry==0.9.2",
]

# [project.optional-dependencies]
# gpu = [
#     "torch>=2.0",
#     "transformers",
#     "accelerate",
# ]

[project.urls]
Homepage = "https://github.com/dataesr/ml-hub"
Documentation = "https://github.com/dataesr/ml-hub"

[project.scripts]
ai-pipeline-run = "ai_core.pipelines.runner:run_pipeline_cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["ai_core*"]

[tool.setuptools.package-data]
ai_core = ["py.typed", "pipelines/configs/*.yaml"]